CREATE TABLE public.profile(
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text NOT NULL,
    age smallint NOT NULL,
    gender public.gender NOT NULL,
    primary_goal public.primary_goal NOT NULL,
    weekly_exercise_days smallint NOT NULL,
    experience_level public.experience_level NOT NULL,
    diet_type public.diet_type NOT NULL,
    allergies allergies[] NOT NULL,
    CONSTRAINT profile_pkey PRIMARY KEY (id)
)
TABLESPACE pg_default;

ALTER TABLE public.profile ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert for everyone" ON public.profile
    FOR INSERT
        WITH CHECK (TRUE);

CREATE POLICY "Enable read access for everyone" ON public.profile
    FOR SELECT
        USING (TRUE);

